apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "jupyter-tensorflow.fullname" . }}"
  annotations: 
    {{- include "chaimeleon.annotations" . | nindent 4 }}
  labels:
    {{- include "jupyter-tensorflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "jupyter-tensorflow.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "jupyter-tensorflow.fullname" . }}"
    spec:
      priorityClassName: processing-applications
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: IfNotPresent
        image: "{{ include "chaimeleon.library-url" . }}/ubuntu-python-tensorflow-desktop-jupyter:{{ .Chart.AppVersion }}"
        ports:
          - containerPort: 2222
            name: sshd
          - containerPort: 5900
            name: vnc-gui
        env:
          # password for "chaimeleon" (OS and SSH) user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "jupyter-tensorflow.fullname" . }}"
                key: container-password

          # password for VNC access (empty username)
          - name: VNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "jupyter-tensorflow.fullname" . }}"
                key: container-password

          # required by jobman
          - name: DATASETS_LIST
            value: "{{ .Values.datasets_list }}"
          - name: JOBMAN_SERVICE_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: "jobman-service-auth"
                key: token

          # required by upload-result
          - name: EXTERNAL_SHARING_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: "external-sharing-service-auth"
                key: url
          - name: EXTERNAL_SHARING_SERVICE_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: "external-sharing-service-auth"
                key: token

          # required by delete-this-desktop 
          - name: HELM_APP_NAME
            value: "{{ .Release.Name }}"

          - name: SSH_ENABLE_PASSWORD_AUTH
            value: "true"
          - name: GATEWAY_PORTS
            value: "true"
          - name: TCP_FORWARDING
            value: "true"
