apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "jupyter-tensorflow.fullname" . }}"
  annotations: 
    {{- include "chaimeleon.annotations" . | nindent 4 }}
  labels:
    {{- include "jupyter-tensorflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "jupyter-tensorflow.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "jupyter-tensorflow.fullname" . }}"
    spec:
      priorityClassName: processing-applications
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.requests.gpu }}
        image: "{{ include "chaimeleon.library-url" . }}/ubuntu-python-tensorflow-desktop-jupyter:{{ .Chart.AppVersion }}cuda11"
        {{- else }}
        image: "{{ include "chaimeleon.library-url" . }}/ubuntu-python-tensorflow-desktop-jupyter:{{ .Chart.AppVersion }}"
        {{- end }}
        resources:
          requests:
            memory: "{{ .Values.requests.memory }}"
            cpu: "{{ .Values.requests.cpu }}"
        {{- if .Values.requests.gpu }}
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        {{- end }}
        
        ports:
          - containerPort: 2222
            name: sshd
          - containerPort: 5900
            name: vnc-gui
        env:
          # password for "chaimeleon" (OS and SSH) user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "jupyter-tensorflow.fullname" . }}"
                key: container-password

          # password for VNC access (empty username)
          - name: VNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "jupyter-tensorflow.fullname" . }}"
                key: container-password

          - name: DATASETS_LIST
            value: "{{ .Values.datasets_list }}"

          - name: SSH_ENABLE_PASSWORD_AUTH
            value: "true"
          - name: GATEWAY_PORTS
            value: "true"
          - name: TCP_FORWARDING
            value: "true"

